import type { AppStore } from "./types";
import { galleryMedia } from "./media";
import { stadiumInfo } from "./data";

export const defaultStore: AppStore = {
  owners: [],
  adminUsers: [],
  blockedDates: [],
  slots: [
    {
      id: "morning",
      date: "",
      label: "Morning Session",
      start: "06:00",
      end: "10:00",
      price: 4500,
      available: true,
      validity: "lifetime",
    },
    {
      id: "day",
      date: "",
      label: "Day Session",
      start: "10:00",
      end: "14:00",
      price: 5500,
      available: true,
      validity: "lifetime",
    },
    {
      id: "afternoon",
      date: "",
      label: "Afternoon Session",
      start: "14:00",
      end: "18:00",
      price: 6000,
      available: true,
      validity: "lifetime",
    },
    {
      id: "evening",
      date: "",
      label: "Evening Session",
      start: "18:00",
      end: "22:00",
      price: 7500,
      available: true,
      validity: "lifetime",
    },
    {
      id: "night",
      date: "",
      label: "Night Session (Floodlights)",
      start: "22:00",
      end: "23:30",
      price: 9000,
      available: false,
      validity: "lifetime",
    },
  ],
  bookings: [],
  ballQualities: [],
  ballPurchases: [],
  ballUsage: [],
  matches: [],
  dieselExpenses: [],
  oldDieselExpenses: [],
  savedMonthlyReports: [],
  otherExpenses: [],
  otherIncomes: [],
  oldExpenses: [],
  oldIncomes: [],
  financeEntries: [],
  gallery: galleryMedia,
  siteContent: {
    aboutTitle: "Muzaffarnagar's Premier Cricket Destination",
    aboutDescription:
      "Crossline Cricket Stadium & Sports Academy offers a professional cricket ground, structured coaching programs, and tournament hosting for players, teams, and organizers across Western UP.",
    aboutPoints: [
      "Professional cricket ground with quality turf wicket",
      "Sports academy with beginner to advanced coaching",
      "Tournament-ready venue with floodlights and facilities",
      "Easy ground booking with admin-confirmed slots",
    ],
    contactEmail: stadiumInfo.email,
    contactPhone: "7500000110",
    contactAddress: stadiumInfo.address,
    contactHours: stadiumInfo.hours,
    testimonials: [
      {
        name: "Rahul Sharma",
        role: "Local League Captain",
        text: "Best ground in Muzaffarnagar. The pitch, floodlights, and staff make every match feel professional.",
        rating: 5,
        type: "player",
      },
      {
        name: "Priya Patel",
        role: "Corporate Cup Organizer",
        text: "We hosted our annual tournament here. Excellent facilities and smooth coordination for 8 teams.",
        rating: 5,
        type: "team",
      },
      {
        name: "Amit Singh",
        role: "Academy Parent",
        text: "My son trains in the evening batch. Coaches are dedicated and the practice nets are top quality.",
        rating: 5,
        type: "academy",
      },
    ],
  },
  tournaments: [
    {
      id: "T1",
      title: "Crossline Premier League 2026",
      date: "2026-06-15",
      description:
        "8-team T20 tournament with prizes for winners and best player awards.",
      status: "upcoming",
      registrationOpen: true,
    },
    {
      id: "T2",
      title: "Weekend Corporate Cup",
      date: "2026-07-05",
      description:
        "Corporate teams welcome. Full ground booking with scoring and refreshments.",
      status: "upcoming",
      registrationOpen: true,
    },
  ],
  academy: {
    headline: "Train Like a Champion",
    description:
      "Structured cricket coaching for all ages — from first-time players to competitive league athletes.",
    programs: [
      {
        id: "A1",
        title: "Beginner Batch",
        description: "Fundamentals of batting, bowling, and fielding for ages 8–14.",
        duration: "3 months",
        level: "beginner",
      },
      {
        id: "A2",
        title: "Advanced League Prep",
        description: "Match simulation, fitness, and tactical training for competitive players.",
        duration: "6 months",
        level: "advanced",
      },
      {
        id: "A3",
        title: "Weekend Intensive",
        description: "Saturday–Sunday focused sessions for working professionals.",
        duration: "8 weeks",
        level: "intermediate",
      },
    ],
  },
  contactMessages: [],
};
